In [114]:
#----------------------------
# make convolution ! 
#----------------------------

import torch
import torchvision
import numpy as np
import matplotlib.pyplot as plt

In [115]:
# dummy data
demo_d = np.asarray( [[0,1,7,5],
[5,5,6,6],
[5,3,3,0],
[1,1,1,2]] ) 

In [116]:
# conv !!

#----------------------
# hyper parameters
filter_size = 2
stride = 2

#----------------------
# dummys
sample = demo_d
tmp_ = []
conv_r = []
conv_m = np.asarray( [[1,0],
    [1,2]] )

#----------------------
# function 
for i in range(0,len(sample[0]) - filter_size + 1 , stride):
    for k in range(0,len(sample[1]) - filter_size + 1 , stride):
        patch = sample[i:i+filter_size,k:k+filter_size]
        re_ = patch * conv_m
        print(patch)

        tmp_.append(patch)
        conv_r.append(np.sum(re_))



[[0 1]
 [5 5]]
[[7 5]
 [6 6]]
[[5 3]
 [1 1]]
[[3 0]
 [1 2]]


In [117]:
# stride 를 위에서 처럼 range 에서 주지 않고, for 문의 var 에다가 곱하면은 
# 최종 matrix 의 행렬값에다가 var 을 바로 넣어서 쓸 수 있다. => to be updated 
conv_r

[15, 25, 8, 8]

In [118]:
# add padding 
pad_size =1

empty_size = len(sample[0]) + (pad_size * 2)
empty_zeros = np.zeros( (empty_size,empty_size) ) 

In [119]:
empty_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [120]:
empty_zeros[0+pad_size : empty_size-pad_size, 0+pad_size : empty_size-pad_size] = sample

In [121]:
empty_zeros

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 7., 5., 0.],
       [0., 5., 5., 6., 6., 0.],
       [0., 5., 3., 3., 0., 0.],
       [0., 1., 1., 1., 2., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [124]:
!git push origin

Username for 'https://github.com': ^C


In [ ]:
!git push origin