In [78]:
mat = [[1,2,1,2],[5,5,5,5],[6,3,6,3]] 
# m x n matrix 
k = 2

In [107]:
origin_mat = np.asarray(mat)
origin_mat

array([[1, 2, 1, 2],
       [5, 5, 5, 5],
       [6, 3, 6, 3]])

In [117]:
mat = [[1,2,1,2],[5,5,5,5],[6,3,6,3]] 
# m x n matrix 
k = 2

#--------------------------------------------
import numpy as np

mat_ = np.asarray(mat)
mat_ori = np.asarray(mat)


#---
que = []

for _ in range(k):
    que.append(mat_[:,-1].copy())
    #print(mat_[:,-1])
    print(que)

    #---
    for col in range(mat_.shape[1]-1, -1, -1):
        
        mat_[:,col] = mat_[:,col-1]

    print("before pop : ", mat_)
    #--- 
    mat_[:,0] = que.pop() 

    print(mat_)


print(mat_ == mat_ori)
print(np.array_equal(mat_, mat_ori))

[array([2, 5, 3])]
before pop :  [[1 1 2 1]
 [5 5 5 5]
 [6 6 3 6]]
[[2 1 2 1]
 [5 5 5 5]
 [3 6 3 6]]
[array([1, 5, 6])]
before pop :  [[2 2 1 2]
 [5 5 5 5]
 [3 3 6 3]]
[[1 2 1 2]
 [5 5 5 5]
 [6 3 6 3]]
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
True
