In [38]:
import torch 

In [44]:
'''
- torch.where 사용법 정리 

1) get indice 
a = torch.tensor([1, 2, 3, 4, 6])
torch.where(a < 4)[0]

2) Boolean mask 
a = torch.tensor([1, 2, 3, 4, 6])
torch.where(a < 4,True,False)

2) 2-d array get indices
a = torch.tensor([[1, 2, 3, 4, 6],[1, 2, 3, 4, 6]])
torch.where(a < 4)[0]
can get row,col tuple ! 

'''

'\n- torch.where 사용법 정리 \n\n1) get indice \na = torch.tensor([1, 2, 3, 4, 6])\ntorch.where(a < 4)[0]\n\n2) Boolean mask \na = torch.tensor([1, 2, 3, 4, 6])\ntorch.where(a < 4,True,False)\n\n2) 2-d array get indices\na = torch.tensor([[1, 2, 3, 4, 6],[1, 2, 3, 4, 6]])\ntorch.where(a < 4)[0]\ncan get row,col tuple ! \n\n'

In [40]:
mat = torch.randn(2,3)

In [41]:
torch.where( mat < 0, True, False)

tensor([[ True,  True, False],
        [False,  True, False]])

In [42]:
a = torch.tensor([1, 2, 3, 4, 6])
torch.where(a < 4)[0]

tensor([0, 1, 2])

In [43]:
a = torch.tensor([1, 2, 3, 4, 6])
torch.where(a < 4,True,False)

tensor([ True,  True,  True, False, False])

In [ ]:
positive_anc_mask = torch.logical_and(iou_mat == max_iou_per_gt_box, max_iou_per_gt_box > 0) 
# condition 2: anchor boxes with iou above a threshold with any of the gt bboxes
positive_anc_mask = torch.logical_or(positive_anc_mask, iou_mat > pos_thresh)

positive_anc_ind_sep = torch.where(positive_anc_mask)[0] # 

# expand gt classes to map against every anchor box
gt_classes_expand = gt_classes_all.view(B, 1, N).expand(B, tot_anc_boxes, N)
# for every anchor box, consider only the class of the gt bbox it overlaps with the most
GT_class = torch.gather(gt_classes_expand, -1, max_iou_per_anc_ind.unsqueeze(-1)).squeeze(-1)