In [1]:
import torch

In [4]:
a = torch.BoolTensor([False, True, True, False])  # or pass [0, 1, 1, 0]
b = torch.BoolTensor([True, True, False, False])

a & b  # logical and
# tensor([False,  True, False, False])

tensor([False,  True, False, False])

In [6]:
c = torch.randn(5)
d = torch.randn(5)
print(c)
print(d)

tensor([-0.6262,  0.1248,  0.9552,  3.1066, -0.7707])
tensor([ 0.1095,  2.0167, -1.5345, -0.7154, -0.5374])


In [8]:
# torch.logical_and(iou_mat == max_iou_per_gt_box, max_iou_per_gt_box > 0) 

torch.logical_and(c < 0, c > -0.65)

tensor([ True, False, False, False, False])