# One-hot encoding 
- numpy   
- torch

In [7]:
import numpy as np 
from keras.utils import to_categorical

a1 = [[7,8,7],[7,10,10],[7,7,7]]
a2 = [[8,7,8],[8,8,8],[8,8,8]]
a3 = [[7,9,9],[6,6,6],[9,9,9]]

a1 =np.asarray(a1)
a2 =np.asarray(a2)

print(a1.shape)
print(a2.shape)

(3, 3)
(3, 3)


In [3]:
zx = np.stack( (a1,a2,a3), axis=0 )
print(zx.shape)

(3, 3, 3)


In [4]:
za = np.argmax(zx, axis=0)

In [6]:
za

array([[1, 2, 2],
       [1, 0, 0],
       [2, 2, 2]])

In [8]:
categorical_labels = to_categorical(za, num_classes= 16 )

In [9]:
categorical_labels

array([[[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]]],
      dtype=float32)

In [10]:
for channel in range(16):
    aa = categorical_labels[:,:,channel]
    print(f"channel : {channel}", aa)

channel : 0 [[0. 0. 0.]
 [0. 1. 1.]
 [0. 0. 0.]]
channel : 1 [[1. 0. 0.]
 [1. 0. 0.]
 [0. 0. 0.]]
channel : 2 [[0. 1. 1.]
 [0. 0. 0.]
 [1. 1. 1.]]
channel : 3 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 4 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 5 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 6 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 7 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 8 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 9 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 10 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 11 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 12 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 13 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 14 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
channel : 15 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
